### ISSUE TITLE
combine several vx masks and/or fcst_leads  together into one column on the scorecard

### ISSUE THREAD

**Issue by lisagoodrich** [NCAR/METviewer#16]
Ben Blake: 
Is it currently possible to combine several vx masks together into one 
column on the scorecard? I split up my verification into the 14 NCEP 
subregions over the CONUS (APL, NEC, SEC, GMC, LMV, MDW, NPL, SPL, NMT, 
SMT, GRB, NWC, SWC, SWD). When making a plot in METViewer, I can select 
all of the regions in the fixed values section, and the generated plot will 
contain statistics over the entire CONUS. I'd like to have one of the 
columns on the scorecard be for CONUS. 

Perhaps there is a way to define the vx_mask I want in the fixed values 
section and then reference it somehow within the columns section?

Logan
Ability to aggregate masking regions to create “super-regions”

Apr. 22 2019

Christina Kalb:
Is it possible to display different lead times in the same column?  For example, if one has a lead of 360000 and another has a lead of 120000, could i display them along the same column
May 2, 2019

Tatiana Burek created issue - 07/Nov/17 3:34 PM

**Comment by TatianaBurek** [comment]
users can group lead times in the columns:
<field name="vx_mask">
        <val name="EAST" label="East"/>
        <field name="fcst_lead">
          <val name="120000,240000" label="12,24"/>
          <val name="360000" label="36"/>
          <val name="480000" label="48"/>
        </field>
      </field>

**Comment by JohnHalleyGotway** [comment]
Email message history:

Ben and Logan,

Tatiana is working on development for this issue:
   https://github.com/NCAR/METviewer/issues/16
This is to enable the use of "groups" in scorecards.  So you might define CONUS as a group of the 14 (or so) subregions.  And then compute the scorecard using the CONUS group instead of the 14 individual subregions.

Tataina and I were talking about a implementation details this morning, and I wanted to let you know what we discussed.  Please let me know if you have any questions about or objections to the following...

Elsewhere in METviewer, users have the choice of computing "summary statistics" or "aggregation statistics".  Let's say our scorecard includes both CSI and RMSE.  A summary CSI value over the 14 subregions would be the mean (or median) of the 14 CSI scores for each region.  An aggregated CSI value is computed by summing up the 14 2x2 contingency tables and then computing a single CSI value from that aggregated table.

Likewise for RMSE, a summary RMSE would be the mean (or median) of the 14 RMSE's for each region.  For an aggregated RMSE, we'd computed the *weighted* average of the SL1L2 partial sums, and then compute a single aggregated RMSE value.

So we are talking about how to define groups in the data as input to the scorecard logic.  And it's obvious to Tatiana and I that we should support the aggregation logic.  The question is whether or not the summary logic applies when constructing these groups.  And my opinion is that no, it does not apply.  A group in the scorecard should be the result of aggregation, not averaging.  While it may be mathematically possible to do the latter, I think it makes the logic too confusing and isn't worthwhile.

Let's say you have MET output for CONUS and the 14 subregions.  With the aggregation logic, a scorecard for CONUS should be identical to a scorecard for the group of 14 subregions... and that's good.  With summary logic, those two would produce different results.

Does this make sense to you as well?

Thanks,
John


Hi John,

What you've proposed makes sense to me as well.  I agree that values for a particular group in the scorecard should be computed via aggregation and not averaging.  If a CONUS scorecard was not identical to a scorecard for the 14 subregions comprising the CONUS, that would also be confusing to me.

Thanks,
Ben

Hi John,

I totally agree with everything that's been said. The aggregation logic should be used so the 'region-aggregated' scorecard matches a CONUS scorecard. Thanks for checking in with us on this.

Thanks,
Logan

**Comment by TatianaBurek** [comment]
Use ":" to separate the field values in the columns that needs to be combined
Only one field can use combined values
